name = "LeanExposition"
version = "0.1.0"
defaultTargets = ["exposition"]

[leanOptions]
autoImplicit = false

[[require]]
name = "verso"
git = "https://github.com/leanprover/verso"
rev = "v4.29.0-rc8"

[[require]]
name = "informal"
git = "https://github.com/mattrobball/lean-informal"
rev = "main"

[[lean_lib]]
name = "LeanExposition"

[[lean_exe]]
name = "exposition"
root = "Main"
supportInterpreter = true
