import Lean

open Lean

namespace LeanExposition

structure TrustedBaseConfig where
  modulePrefix : Name
  excludeModulePrefixes : Array Name := #[]
  includeAutoGenerated : Bool := false
deriving Repr

structure TrustedBaseResult where
  typeDeps : NameSet := {}
  valueDeps : NameSet := {}

private def isAuxComponent (s : String) : Bool :=
  s.startsWith "_" || s.startsWith "match_" || s.startsWith "proof_" || s.startsWith "eq_"

private partial def hasPrefix (n prefixName : Name) : Bool :=
  n == prefixName || match n with
    | .str p _ => hasPrefix p prefixName
    | .num p _ => hasPrefix p prefixName
    | .anonymous => false

private partial def isInternalName : Name → Bool
  | .anonymous => false
  | .num p _ => isInternalName p
  | .str p s =>
      isAuxComponent s
      || s ∈ ["brecOn", "below", "casesOn", "noConfusion", "noConfusionType",
              "recOn", "rec", "ind", "mk", "sizeOf_spec", "inject", "injEq",
              "ctorIdx", "ext_iff"]
      || isInternalName p

private def isInReportedModule (env : Environment) (cfg : TrustedBaseConfig) (c : Name) : Bool :=
  match env.getModuleIdxFor? c with
  | some modIdx =>
      let modName := env.header.moduleNames[modIdx.toNat]!
      hasPrefix modName cfg.modulePrefix
      && !cfg.excludeModulePrefixes.any (hasPrefix modName ·)
  | none => false

private def shouldReport (env : Environment) (cfg : TrustedBaseConfig) (c : Name) : Bool :=
  if !isInReportedModule env cfg c then
    false
  else if cfg.includeAutoGenerated then
    true
  else if isInternalName c then
    false
  else if isAuxRecursor env c || isNoConfusion env c then
    false
  else
    match env.find? c with
    | some (.ctorInfo _) | some (.recInfo _) | some (.quotInfo _) => false
    | _ => true

structure CollectState where
  visited : NameSet := {}
  typeDeps : NameSet := {}

abbrev CollectM := ReaderT (Environment × TrustedBaseConfig) (StateM CollectState)

private def collectExpr (e : Expr) (collect : Name → CollectM Unit) : CollectM Unit :=
  e.getUsedConstants.forM collect

private partial def collect (c : Name) : CollectM Unit := do
  let s ← get
  if s.visited.contains c then
    return
  modify fun s => { s with visited := s.visited.insert c }
  let (env, cfg) ← read
  match env.find? c with
  | some (.defnInfo v) =>
      if shouldReport env cfg c then
        modify fun s => { s with typeDeps := s.typeDeps.insert c }
      collectExpr v.type collect
      collectExpr v.value collect
  | some (.thmInfo v) =>
      if shouldReport env cfg c then
        modify fun s => { s with typeDeps := s.typeDeps.insert c }
      collectExpr v.type collect
  | some (.opaqueInfo v) =>
      if shouldReport env cfg c then
        modify fun s => { s with typeDeps := s.typeDeps.insert c }
      collectExpr v.type collect
      collectExpr v.value collect
  | some (.inductInfo v) =>
      if shouldReport env cfg c then
        modify fun s => { s with typeDeps := s.typeDeps.insert c }
      collectExpr v.type collect
      v.ctors.forM collect
  | some (.ctorInfo v) =>
      if shouldReport env cfg c then
        modify fun s => { s with typeDeps := s.typeDeps.insert c }
      collectExpr v.type collect
  | some (.recInfo v) =>
      if shouldReport env cfg c then
        modify fun s => { s with typeDeps := s.typeDeps.insert c }
      collectExpr v.type collect
  | some (.axiomInfo v) =>
      if shouldReport env cfg c then
        modify fun s => { s with typeDeps := s.typeDeps.insert c }
      collectExpr v.type collect
  | some (.quotInfo _) => pure ()
  | none => pure ()

def extractTrustedBase (env : Environment) (cfg : TrustedBaseConfig) (target : Name) : TrustedBaseResult := Id.run do
  let some info := env.find? target | return {}
  let mut s : CollectState := {}
  (_, s) := ((collectExpr info.type collect : CollectM Unit).run (env, cfg)).run s
  let typeDeps := s.typeDeps
  match info with
  | .defnInfo v =>
      (_, s) := ((collectExpr v.value collect : CollectM Unit).run (env, cfg)).run s
  | .opaqueInfo v =>
      (_, s) := ((collectExpr v.value collect : CollectM Unit).run (env, cfg)).run s
  | .inductInfo v =>
      (_, s) := ((v.ctors.forM collect : CollectM Unit).run (env, cfg)).run s
  | _ => pure ()
  let allDeps := s.typeDeps
  let valueDeps := allDeps.diff typeDeps
  { typeDeps, valueDeps }

def extractTrustedBaseNames (env : Environment) (cfg : TrustedBaseConfig)
    (targets : Array Name) : Std.HashSet Name :=
  Id.run do
    let mut names : Std.HashSet Name := {}
    for target in targets do
      let result := extractTrustedBase env cfg target
      for name in result.typeDeps.toArray do
        names := names.insert name
    names

end LeanExposition
